version: "3"

services:
  pdv-app:
    build: .
    container_name: pdv-app
    volumes:
      - ./:/app
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - mysql-db
    command: sh -c "./install.sh"
  mysql-db:
    image: mysql:8.0.30
    container_name: mysql-db
    volumes:
      - ./:/mysql
    environment:
      MYSQL_ROOT_HOST: 'localhost'
      MYSQL_DATABASE: 'pdv'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'secretroot'
    ports:
      - "3306:3306"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
