version: "3"

services:
  pdv-app:
    build: .
    container_name: pdv-app
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - mysql-db
    command: sh -c "./install.sh"
  mysql-db:
    image: mysql:8.0.30
    container_name: mysql-db
    volumes:
      - ./:/mysql
    environment:
      MYSQL_ROOT_HOST: '${DB_HOST}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
